name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Richter06
          outputs: |
            dist/github-snake-gold.svg?color_snake=%239B6F08&color_dots=%23FFFDF8,%23F3E8C0,%23DDBB55,%23C49A2D,%239B6F08

      - name: Commit generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update github contribution snake"
          add: "dist/github-snake-gold.svg"
